insert into SKILL (SKILL_ID,SKILL_NAME,SKILL_DESCRIPTION) values(1,'JAVA','JAVA STACK');
insert into SKILL (SKILL_ID,SKILL_NAME,SKILL_DESCRIPTION) values(2,'Full Stack','JAVA Full Stack');
insert into SKILL (SKILL_ID,SKILL_NAME,SKILL_DESCRIPTION) values(3,'DevOps','DevOps');


insert into COURSES (COURSE_ID,ACTIVITY_TYPE,COURSE_NAME,DESCRIPTION,IS_LICENSE_NEEDED,PROFICIENCY_LEVEL,CREATION_DATE,STATUS,SKILL_ID) values (100,'Self Paced','Java 14 New Features','New features of Java 14 Release',false,3,'2020-09-01','ACTIVE',1);
insert into COURSES (COURSE_ID,ACTIVITY_TYPE,COURSE_NAME,DESCRIPTION,IS_LICENSE_NEEDED,PROFICIENCY_LEVEL,CREATION_DATE,STATUS,SKILL_ID) values (101,'SkillSoft','Java Desgin patterns','Java Desgin patterns',false,4,'2020-08-29','ACTIVE',1);
insert into COURSES (COURSE_ID,ACTIVITY_TYPE,COURSE_NAME,DESCRIPTION,IS_LICENSE_NEEDED,PROFICIENCY_LEVEL,CREATION_DATE,STATUS,SKILL_ID)values (102,'External Certification','OCJP','Java Professional Certification',true,5,'2020-08-29','ACTIVE',1);

insert into COURSES (COURSE_ID,ACTIVITY_TYPE,COURSE_NAME,DESCRIPTION,IS_LICENSE_NEEDED,PROFICIENCY_LEVEL,CREATION_DATE,STATUS,SKILL_ID) values (103,'Udemy','React essentials','React JS',false,4,'2020-08-25','ACTIVE',2);
insert into COURSES (COURSE_ID,ACTIVITY_TYPE,COURSE_NAME,DESCRIPTION,IS_LICENSE_NEEDED,PROFICIENCY_LEVEL,CREATION_DATE,STATUS,SKILL_ID)values (104,'Self Paced','Angular','Angular 101',false,2,'2020-08-23','ACTIVE',2);
insert into COURSES (COURSE_ID,ACTIVITY_TYPE,COURSE_NAME,DESCRIPTION,IS_LICENSE_NEEDED,PROFICIENCY_LEVEL,CREATION_DATE,STATUS,SKILL_ID) values (105,'CCP','FSE','Cognizant Certified Full stack Developer',false,5,'2019-05-05','Active',2);

insert into COURSES (COURSE_ID,ACTIVITY_TYPE,COURSE_NAME,DESCRIPTION,IS_LICENSE_NEEDED,PROFICIENCY_LEVEL,CREATION_DATE,STATUS,SKILL_ID) values (106,'Self Paced','DevOps-101','Know about DevOps practice',false,1,'2018-05-05','ACTIVE',3);
insert into COURSES (COURSE_ID,ACTIVITY_TYPE,COURSE_NAME,DESCRIPTION,IS_LICENSE_NEEDED,PROFICIENCY_LEVEL,CREATION_DATE,STATUS,SKILL_ID) values (107,'Udemy','DevOps Zero to Hero','A complete tutorial on DevOps',false,4,'2020-07-09','Expired',3);



