spring:
  application:
    name: zuul-proxy
server:
  port: 8888
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKASERVER_URI}
management:
  endpoints:
    web:
      exposure:
        include: routes
zuul:
  routes:
    license-service: /license/**
hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 15000
token.secret: 4564fa2!!rrxx44555^^^



