spring:
  application:
    name: auth-service
server:
    port: 9100
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
